language: csharp
dotnet: 2.0.0
mono: latest
cache:
  directories:
  - Paket
script:
  allow_failures:
  - git clone https://github.com/fsprojects/Paket.git
 - cd Paket
 - sudo ./install.sh
 - cd ..
 - paket update
 - dotnet run --project ArmEmulator/ArmEmulator.fsproj