language: csharp
dotnet: 2.0.0
mono: latest
cache:
  directories:
  - Paket
before_script:
- git clone https://github.com/fsprojects/Paket.git
script:
 - cd Paket
 - sudo ./install.sh
 - cd ..
 - paket update
 - dotnet run --project ArmEmulator/ArmEmulator.fsproj